### ISSUE TITLE
Help to understand 

### ISSUE THREAD

**Issue by joe2707** [bljohnsondev/comcutter#1]
Hi
Can you help me to understand this better ?
I've built container with docker compose as per the readme but how do I generate an API to use with the script ?

And do I put the script into an sh file chmod +X the file and put the path in the post processing script box within emby ?

Any advice is much appreciated.

Thanks

**Comment by bljohnsondev** [comment]
Hi there!

The docker container that gets created has the API endpoint you need to call from your Emby server.

You then need to create a shell script like the one I provided in the example and that script needs to be available in your Emby container.  I'm using Jellyfin and what I did was create a volume mount that mounts a folder that has the script in it to something like `/scripts`.  So let's assume you called your script `call-comcutter.sh`.

I haven't used Emby but with Jellyfin you go to the *Admin Dashboard* and under "DVR" there is a setting called `Post-processing application`.  In there you would set that to `/scripts/call-comcutter.sh`.

When a recording gets done it will run that script which makes an API call to your comcutter container that starts the process of stripping out the commercials.

One thing to remember is that the comcutter API really wants the **relative** path (relative to your media folder) to the file that was recorded.  I really should update the examples to make this more clear.

So, let's say you have a volume mount in your Emby container to `/data/media` where your media library resides and you just got done recording a Family Guy episode.  It records to `/data/media/dvr/Family Guy/Season 22/Family Guy S22E05 Old World Harm.ts`.  It will send this **full path** to comcutter given the example I posted.

You only want to send the **relative path** without the `/data/media` part.  In this example you only want to send `dvr/Family Guy/Season 22/Family Guy S22E05 Old World Harm.ts`.

How I do this is with the following script as an example.

```sh
#!/bin/bash

filepath="$@"

# example file - '/data/media/dvr/Family Guy/Season 22/Family Guy S22E05 Old World Harm.ts'
stripped=`echo "$filepath" | cut -c 12-`

curl -X POST \
  http://localhost:9090/comskip \
  -H 'Content-Type: application/json' \
  -d "{\"api\": \"ABC123\", \"file\": \"${stripped}\"}"
```

This will strip out `/data/media` (the `cut -c 12-` part removes the first 12 characters) and only send the rest of the path to comcutter.  Then just make sure you create a volume mount in comcutter that maps `/data/media` to `/library` (or whatever you set if you changed the `library_dir` config variable).

Does that help or did I confuse you even more?  Let me know if you have any other questions and I'll do my best to help.

**Comment by bljohnsondev** [comment]
You just need to generate a key.  You can choose something yourself or in Linux you can run a command like `echo $RANDOM | md5sum | head -c 20; echo;` that will create a randomly generated 20 character string.

Use that string in the `curl` command in the shell script to pass that to the API and make sure you set the same key in the `config.yml` file (the `apikey` setting).  It checks for a matching key before processing the request.  The `config.yml` file should get auto generated for you with sample values the first time the container runs.

**Comment by bljohnsondev** [comment]
I've updated the README to include more information related to absolute and relative paths used in the script.  I'm going to close this issue.  If you have any more questions let me know.
